IS_CS/Models/Grazinima.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grazinima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grazinima()
        {
            this.Patvirtinimas = new HashSet<Patvirtinima>();
            this.Uzsakymas = new HashSet<Uzsakyma>();
        }
    
        public int nr { get; set; }
        public System.DateTime data { get; set; }
        public string grazinimo_aprasymas { get; set; }
        public int fk_grazinimo_priezastis { get; set; }
        public int fk_Klientas_paskyros_id { get; set; }
        public int fk_Grazinimo_busena { get; set; }
    
        public virtual Grazinimo_priezastis Grazinimo_priezastis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patvirtinima> Patvirtinimas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzsakyma> Uzsakymas { get; set; }
        public virtual Grazinimo_busena Grazinimo_busena { get; set; }
    }
}

IS_CS/Models/Israsa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Israsa
    {
        public int nr { get; set; }
        public System.DateTime data { get; set; }
        public int fk_Patvirtinimas { get; set; }
        public int fk_Klientas_paskyros_id { get; set; }
    
        public virtual Klienta Klienta { get; set; }
        public virtual Patvirtinima Patvirtinima { get; set; }
    }
}

IS_CS/Controllers/GrazinimasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IS_CS.Models;

namespace IS_CS.Controllers
{
    public class GrazinimasController : Controller
    {
        private is_kpEntities1 _entities = new is_kpEntities1();

        public ActionResult prekiu_grazinimas()
        {
            return View(_entities.Uzsakymas.ToList());
        }

        public ActionResult grazinimo_formos()
        {
            return View(_entities.Uzsakymas.ToList());
        }

        public ActionResult israsas()
        {
            return View(_entities.Uzsakymas.ToList());
        }

        public ActionResult grazinimo_patvirtinimas()
        {
            return View(_entities.Patvirtinimas.ToList());
        }

        public ActionResult grazinimas_create()
        {
            Grazinima grazinima = new Grazinima();
            return View(grazinima); ;
        }
        [HttpPost]
        public ActionResult grazinimas_create(Grazinima newGrazinimas)
        {
            if (ModelState.IsValid)
            {
                _entities.Grazinimas.Add(newGrazinimas);
                _entities.SaveChanges();
            }
            return RedirectToAction("grazinimo_formos");
        }

        public ActionResult israsas_edit(int israsas)
        {
            Israsa israsa = _entities.Israsas.Find(israsas);
            if (israsa == null)
            {
                return HttpNotFound();
            }
            return View(israsa);
        }
        [HttpPost]
        public ActionResult israsas_edit(Israsa israsa)
        {
            if (ModelState.IsValid)
            {
                _entities.Entry(israsa).State = System.Data.Entity.EntityState.Modified;
                _entities.SaveChanges();
                return RedirectToAction("grazinimo_formos");
            }
            return View(israsa);
        }
    }
}

IS_CS/Views/Grazinimas/grazinimas_create.cshtml
@model IS_CS.Models.Grazinima

@{
    ViewBag.Title = "Grazinimas_create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Grąžinimo formos užpildymas</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Grąžinimo forma</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <a>Nr.</a>
        <div class="col-md-10">
            @Html.EditorFor(model => model.nr, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nr, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <a>Data</a>
        <div class="col-md-10">
            @Html.EditorFor(model => model.data, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.data, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <a>Grąžinimo aprašymas</a>
        <div class="col-md-10">
            @Html.EditorFor(model => model.grazinimo_aprasymas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.grazinimo_aprasymas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <a>Grąžinimo priežastis</a>
        <div class="col-md-10">
            @Html.EditorFor(model => model.fk_grazinimo_priezastis, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fk_grazinimo_priezastis, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <a>Kliento id</a>
        <div class="col-md-10">
            @Html.EditorFor(model => model.fk_Klientas_paskyros_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fk_Klientas_paskyros_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <a>Grąžinimo būsena</a>
        <div class="col-md-10">
            @Html.EditorFor(model => model.fk_Grazinimo_busena, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fk_Grazinimo_busena, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Sukurti" class="btn btn-default" />
        </div>
    </div>
</div>
}

IS_CS/Views/Grazinimas/grazinimo_formos.cshtml
@model IEnumerable<IS_CS.Models.Uzsakyma>
@{
    ViewBag.Title = "Grąžinimo formos";
}

<table style="width:100%" id="formos">
    <tr>
        <th>
            Nr.
        </th>
        <th>
            Formos pateikimo data
        </th>
        <th>
            Kliento vardas ir pavardė
        </th>
        <th>
            Grąžinamo užsakymo nr.
        </th>
        <th>
            Grąžinimo priežastis
        </th>
        <th>
            Grąžinimo aprašymas
        </th>
        <th>
            Grąžinimo būsena ir pakeitimo data
        </th>
        <th>
        </th>
        <th>
        </th>
    </tr>
    <br>
    <br>

    @foreach (var item in Model)
    {
        if (item.fk_Grazinimo_nr != null)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Grazinima.nr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grazinima.data.Year)-@Html.DisplayFor(modelItem => item.Grazinima.data.Month)-@Html.DisplayFor(modelItem => item.Grazinima.data.Day)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Klienta.vardas) @Html.DisplayFor(modelItem => item.Klienta.pavarde)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fk_Grazinimo_nr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grazinima.Grazinimo_priezastis.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grazinima.grazinimo_aprasymas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grazinima.Grazinimo_busena.Grazinimo_busenos.name), @Html.DisplayFor(modelItem => item.Grazinima.Grazinimo_busena.busenos_pakeitimo_data.Year)-@Html.DisplayFor(modelItem => item.Grazinima.Grazinimo_busena.busenos_pakeitimo_data.Month)-@Html.DisplayFor(modelItem => item.Grazinima.Grazinimo_busena.busenos_pakeitimo_data.Day)
                </td>
                <td>@Html.ActionLink("Išrašas", "israsas", "Grazinimas", new { israsas = @Html.DisplayFor(modelItem => item.uzsakymo_id) }, null)</td>
                <td>@Html.ActionLink("Patvirtinimas/Būsenos keitimas", "grazinimo_patvirtinimas", "Grazinimas", new { grazinimas = @Html.DisplayFor(modelItem => item.Grazinima.nr) }, null)</td>




            </tr>
        }
    }

</table>

IS_CS/Views/Grazinimas/grazinimo_patvirtinimas.cshtml
@model IEnumerable<IS_CS.Models.Patvirtinima>
@{
    ViewBag.Title = "Grąžinimo patvirtinimas";
}
<div>
    @foreach (var item in Model)
    {
        if (item.fk_Graznimas_nr.ToString() == Request.QueryString["grazinimas"])
        {
            <h2 id="pageTitle">Prekės grąžinimo patvirtinimas/būsenos keitimas:</h2>
            if (item.ar_preke_gali_buti_grazinta == 0)
            {
                <form action="#" method="get" id="patvirtinti">
                    <fieldset>
                        <legend>Prekės grąžinimo patvirtinimas:</legend>
                        Ar prekė gali būti grąžinta:<br>
                        <input type="radio" name="p" value="0" checked>Taip<br>
                        <input type="radio" name="p" value="1">Ne<br>
                        <button type="submit" form="patvirtinti" value="Submit">Išsaugoti</button>
                    </fieldset>
                </form><br>
            }
            else
            {

                <form action="#" method="get" id="patvirtinti">
                    <fieldset>
                        <legend>Prekės grąžinimo patvirtinimas:</legend>
                        Ar prekė gali būti grąžinta:<br>
                        <input type="radio" name="p" value="0">Taip<br>
                        <input type="radio" name="p" value="1" checked>Ne<br>
                        <button type="submit" form="patvirtinti" value="Submit">Išsaugoti</button>
                    </fieldset>
                </form><br>
            }


            <form action="#" method="get" id="busena" name="busena">
                <fieldset>
                    <legend>Prekės grąžinimo būsena:</legend>
                    <select>
                        <option value="1">Laukiama patvirtinimo</option>
                        <option value="2">Patvirtintas</option>
                        <option value="3">Vykdomas</option>
                        <option value="4">Užbaigtas</option>
                        <option value="5">Atmestas</option>
                    </select><br><br>
            </form><br>
            <button type="submit" form="busena" value="Submit">Išsaugoti</button>


        }
    }
</div>

IS_CS/Views/Grazinimas/israsas.cshtml
@model IEnumerable<IS_CS.Models.Uzsakyma>

@{
    ViewBag.Title = "Išrašas";
}
<div>
    <form action="#" method="get" id="forma">
        <br>
        <fieldset>
            <legend>Grąžinimo formos išrašas:</legend><br>
            <tr>
                @foreach (var item in Model)
                {
                    if (item.uzsakymo_id.ToString() == Request.QueryString["israsas"])
                    {
                        <th>Užsakymo nr.: </th>
                        <td>@Html.DisplayFor(modelItem => item.uzsakymo_id)</td>
                        <br>
                        <th>Data: </th>
                        <td></td>
                        <br>
                        <th>Kliento vardas ir pavardė: </th>
                        <td> @Html.DisplayFor(modelItem => item.Klienta.vardas) @Html.DisplayFor(modelItem => item.Klienta.pavarde)</td>
                        <br>
                        <th>Darbuotojo vardas ir pavardė: </th>
                        <td>@Html.DisplayFor(modelItem => item.Darbuotoja.vardas) @Html.DisplayFor(modelItem => item.Darbuotoja.pavarde)</td>
                        <br>
                        <th>Grąžinimo priežastis: </th>
                        <td>@Html.DisplayFor(modelItem => item.Grazinima.Grazinimo_priezastis.name)</td>
                        <br>
                        <th>Grąžinimo būsena: </th>
                        <td>@Html.DisplayFor(modelItem => item.Grazinima.Grazinimo_busena.Grazinimo_busenos.name)</td>
                        <br>
                    }
                }
            </tr>
        </fieldset>
    </form><br>
    @Html.ActionLink("Pildyti/redaguoti išrašą", "israsas_edit", new { israsas = @Html.DisplayFor(modelItem => Request.QueryString["israsas"]) })
    <button type="button">Siųsti išrašą klientui</button>
</div>

IS_CS/Views/Grazinimas/israsas_edit.cshtml
@model IS_CS.Models.Israsa

@{
    ViewBag.Title = "Išrašas";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Išrašas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <a>Nr.</a>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <a>Data</a>
            <div class="col-md-10">
                @Html.EditorFor(model => model.data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <a>Patvirtinimas</a>
            <div class="col-md-10">
                @Html.EditorFor(model => model.fk_Patvirtinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fk_Patvirtinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <a>Klientas</a>
            <div class="col-md-10">
                @Html.EditorFor(model => model.fk_Klientas_paskyros_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fk_Klientas_paskyros_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Išsaugoti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grižti", "israsas", "Grazinimas", new { israsas = @Html.DisplayFor(modelItem => Request.QueryString["israsas"]) }, null) </ td >
</div>

IS_CS/Views/Grazinimas/prekiu_grazinimas.cshtml
@model IEnumerable<IS_CS.Models.Uzsakyma>

@{
    ViewBag.Title = "Registracija grąžinimui";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div>
        <h2 id="pageTitle">Prekių registracija grąžinimui:</h2>
        <form action="#" method="get" id="forma">
            <fieldset>
                <legend>Prekės grąžinimo forma:</legend>
                Grąžinimo priežastis:<br>
                <input type="radio" name="priezastis" value="bloga" checked> Boga kokybė<br>
                <input type="radio" name="priezastis" value="neta"> Gauta ne ta prekė<br>
                <input type="radio" name="priezastis" value="pazeista"> Pažeista prekė<br>
                <input type="radio" name="priezastis" value="nemokamas"> Nemokamas 14d. grąžinimas<br><br>
                <br>
                Grąžinamo užsakymo nr:<br>
                <select>
                    @foreach (var item in Model)
                    {
                        if (item.fk_Grazinimo_nr == null)
                        {


                            <option name="uzsakymas" value=@Html.DisplayFor(modelItem => item.uzsakymo_id)>@Html.DisplayFor(modelItem => item.uzsakymo_id)</option>

                        }
                    }
                </select><br><br>

                <label>Platesnis grąžinimo priežasties aprašymas:<br></label>
                <textarea name="aprasymas" id="aprasymas" rows="6" cols="60" class="field-long field-textarea"></textarea>
            </fieldset>
        </form><br><br>
        <button type="submit" form="forma" value="Submit">Pateikti</button>
    </div>
}